# Generated by Django 5.1.1 on 2024-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
